repos:
  - repo: https://github.com/google/yapf
    rev: v0.31.0
    hooks:
      - id: yapf
        args: [-ir, .]
        additional_dependencies: ["toml"]
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
