[tool.yapf]
align_closing_bracket_with_visual_indent = true
allow_multiline_lambdas = true
allow_multiline_dictionary_keys = true
allow_split_before_default_or_named_assigns = false
allow_split_before_dict_value = false
arithmetic_precedence_indication = false
blank_line_before_nested_class_or_def = false
blank_line_before_module_docstring = false
blank_line_before_class_docstring = false
blank_lines_around_top_level_definition = 2
blank_lines_between_top_level_imports_and_variables = 2
coalesce_brackets = true
column_limit = 120
continuation_align_style = "space"
dedent_closing_brackets = true
disable_ending_comma_heuristic = true
each_dict_entry_on_separate_line = false
force_multiline_dict = false
indent_dictionary_value = true
indent_width = 4
indent_blank_lines = false
indent_closing_brackets = false
join_multiple_lines = false
spaces_around_power_operator = false
spaces_around_default_or_named_assign = false
spaces_around_dict_delimiters = false
spaces_around_list_delimiters = false
spaces_around_subscript_colon = false
spaces_before_comment = 2
space_between_ending_comma_and_closing_bracket = false
space_inside_brackets = false
split_arguments_when_comma_terminated = false
split_all_comma_separated_values = false
split_all_top_level_comma_separated_values = true
split_before_bitwise_operator = true
split_before_arithmetic_operator = true
split_before_closing_bracket = true
split_before_dict_set_generator = true
split_before_dot = true
split_before_first_argument = true
split_before_logical_operator = true
split_before_named_assigns = false
split_complex_comprehension = true
use_tabs = false
